// Copies pdf.js (installed from npm) into a module the app can load into its
// offline WebView, so reading lab report PDFs never needs the internet.
// Runs after `npm install`; the output is generated, so it isn't committed.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const build = path.join(root, 'node_modules', 'pdfjs-dist', 'legacy', 'build');
const out = path.join(root, 'src', 'lib', 'extract', 'pdfjsSource.generated.ts');

const lib = fs.readFileSync(path.join(build, 'pdf.min.mjs'), 'utf8');
const worker = fs.readFileSync(path.join(build, 'pdf.worker.min.mjs'), 'utf8');
const { version } = require('pdfjs-dist/package.json');

fs.writeFileSync(
  out,
  `// Generated by scripts/vendor-pdfjs.js from pdfjs-dist ${version}. Do not edit.\n` +
    `export const PDFJS_VERSION = ${JSON.stringify(version)};\n` +
    `export const PDFJS_LIB = ${JSON.stringify(lib)};\n` +
    `export const PDFJS_WORKER = ${JSON.stringify(worker)};\n`
);
console.log(`pdf.js ${version} vendored to ${path.relative(root, out)}`);
